spring:
  datasource:
    database-key-name: site5-dev-lego
  liquibase:
    parameters:
      environment-schema: lego_dev

target-database:
  datasource:
    database-key-name: legolandserver1-lego-dev