import-path: /dev/config

spring:
  jmx:
    enabled: false
  application:
    name: Lego Database DB Deployer
  main:
    web-application-type: none
  config:
    import: optional:file:${import-path}/database-configuration.yml

logging:
  level:
    root: INFO
