spring:
  jmx:
    enabled: false
  application:
    name: Lego Database DB Deployer
  datasource:
    hikari:
      connection-timeout: 10000
      idle-timeout: 30000
      connection-test-query: SELECT 1
      initialization-fail-timeout: 10000
      auto-commit: false
      login-timeout: 10000
      minimum-idle: 30
      maximum-pool-size: 30
      validation-timeout: 10000
      pool-name: source-mysql-jdbc-pool
  main:
    web-application-type: none
  config:
    import: file:/dev/config/bricklink/bricklink-client-api-keys.yml, file:/dev/config/bricklink/bricklink-web.yml, file:/dev/config/database/database-configuration.yml

target-database:
  datasource:
    hikari:
      connection-timeout: 10000
      idle-timeout: 30000
      connection-test-query: SELECT 1
      initialization-fail-timeout: 10000
      auto-commit: false
      login-timeout: 10000
      minimum-idle: 5
      maximum-pool-size: 5
      validation-timeout: 300000
      pool-name: target-mysql-jdbc-pool

bricklink:
  rest:
    uri: https://api.bricklink.com/api/store/v1
  web:
    pool:
      default-max-per-route: 20
      max-per-route: 20
      max-total: 50

logging:
  level:
    root: INFO
    org.apache.http.client.protocol: ERROR

postprocessors:
  groups:
    migration-1.0-to-2.0:
      - InitialMigrationPostProcessor
      - CategoryMigrator
      - ConditionMigrator
      - TransactionTypeMigrator
      - CarrierMigrator
      - TransactionPlatformMigrator
      - CostTypeMigrator
      - PartyMigrator
      - PaymentPlatformMigrator
      - ExternalServiceTypeMigrator
      - ExternalServiceMigrator
      - InventoryIndexMigrator
      - ItemMigrator
#      - BricklinkExternalItemMigrator
#      - BricklinkExternalServiceItemMigrator
      - ItemInventoryMigrator
      - ExternalItemInventoryMigrator
      - BricklinkItemInventoryMigrator
